### ISSUE TITLE
Weird-looking faces after 15h of training

### ISSUE THREAD

**Issue by stoppedworking** [deepfakes/faceswap-model#10]
Hello everyone,

after 15h of (GPU-)training the model generates those faces:
![werid](https://user-images.githubusercontent.com/35898656/35485226-c1f50f1c-045c-11e8-9e3e-944987e59f3b.png)
![weird2](https://user-images.githubusercontent.com/35898656/35485243-0e6a6e5a-045d-11e8-84e4-1ae3fdb9a060.png)
![weird3](https://user-images.githubusercontent.com/35898656/35485265-41c51548-045d-11e8-9779-467ddaf18723.png)

You can clearly see the border between the real and the fake face. Additionally, the resolution of the fake face is much lower than the resolution of the source image. `BATCH_SIZE` is set to 64. Does increasing the `BATCH_SIZE` (for example to 256) improve the image-quality/realness or does the model just need more training?

GIFs on r/deepfakes look far more real, than those pictures. What am I doing wrong?

Edit:

(sorry for the dumb question) What do the model weights/the two printed numbers in the console mean? They are `0.008821762 0.0131980395`.

I trained the model with about 5k of each person, which I extracted from 2 videos.

**Comment by Clorr** [comment]
The output of the scripts is 64*64px images. Discussions and PRs are made to go higher (128*128px) but there is nothing official yet. Training more or increasing the batch_size won't help you.

What you can improve here is the way you merge/convert your pics. You should look in issues to see if people had similar issues and they solved it (for example: https://github.com/deepfakes/faceswap/issues/85)

About the output values, what you show is the `loss value`, a number that shows how "precise" your model is. Being close to 0.01 on both side is quite nice already...
