### ISSUE TITLE
Improve convert script efficiency

### ISSUE THREAD

**Issue by Yutsa** [deepfakes/faceswap-model#8]
Hello everyone,

I noticed that the training script uses every core I have on my CPU but the convert script must be using only one as I see a low CPU usage. Because of that, converting a lot of pictures is really long on CPU.

Is it possible to use multi-threading to speed things up ? Or the way we do the conversion prevents that ?

**Comment by Clorr** [comment]
I'm closing this as it is not strictly "model" related, but the question is still open
